version: '3.3'
services:
  fabscan:
    build:
      context: docker/
      dockerfile: Dockerfile
    container_name: fabscan
    ports:
      - 8080:8080
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    volumes:
      - ./src/:/fabscan/src
      - ./dummy/:/fabscan/dummy
    command: ["/fabscan/src/fabscanpi-server", "--loglevel=debug", "--config=/fabscan/src/fabscan/config/dummy.config.json","--settings=/fabscan/src/fabscan/config/default.settings.json"]